### ISSUE TITLE
Tried to Make a Reset button, but it bombs out

### ISSUE THREAD

**Issue by tgwaste** [lupyuen/visual-embedded-rust#1]
![reset](https://user-images.githubusercontent.com/690918/74792383-86d7d180-527a-11ea-9a10-75460f7a4d23.jpg)

**Comment by lupyuen** [comment]
Sorry, the infer_type macro has been fixed to handle multiple labels and buttons. Get the latest macro like this...

cd ~/pinetime-rust-mynewt
git pull --recurse-submodules
