### ISSUE TITLE
Wiring issue

### ISSUE THREAD

**Issue by TechnologyClassroom** [lupyuen/visual-embedded-rust#4]
Sorry if this is not the right place for this.  I am trying to follow this wiring diagram to get [pinetime-updater](https://github.com/lupyuen/pinetime-updater/) working.  I followed the diagram the same was as the pictures using a Pi 0 WH after enabling SPI.

Once I connect the 3.3V, the RPi forgets everything.  Every command returns a variation of this:

    -bash: /usr/bin/ls: Input/output error

I can unplug and replug and SSH back into the machine.  Commands work again until, I plug in the 3.3V.

Any ideas?

**Comment by lupyuen** [comment]
Hi: Sorry I'm no longer supporting PineTime, could you check with the PineTime chatroom on Matrix / Discord / Telegram / IRC? 

https://wiki.pine64.org/index.php/PineTime#Chat 

Also the Visual Embedded Rust code is obsolete, so it will no longer work. But pinetime-updater should still work. Thanks.
